console.log('Date object in js')

let today=new Date()
console.log(today)

let otherDay=new Date('9-10-2012 04:12:6')
console.log(otherDay)

otherDay=new Date('June 17 1999')
console.log(otherDay)

otherDay=new Date('12/12/2012')
console.log(otherDay)
console.log(otherDay.getDate())
console.log(otherDay.getDay())
console.log(otherDay.getFullYear())
console.log(otherDay.getMinutes())
console.log(otherDay.getSeconds())
console.log(otherDay.getHours())
console.log(otherDay.getMilliseconds()) 
console.log(otherDay.getTime())
console.log(otherDay.getMonth())
otherDay.setDate(1)
otherDay.setFullYear(1911)
otherDay.setMonth(4)
console.log(otherDay)
otherDay.setMinutes(1)
otherDay.setHours(1)
otherDay.setSeconds(4)
console.log(otherDay)